# Generated by Django 5.0.6 on 2024-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('alpha2', models.CharField()),
                ('alpha3', models.CharField()),
                ('region', models.CharField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
    ]
